(() => {
  const body = document.querySelector('body');
  const allDivs = document.querySelectorAll('div')
  const allH1 = document.querySelectorAll('h1')
  const allH2 = document.querySelectorAll('h2')
  const allH3 = document.querySelectorAll('h3')
  const allH4 = document.querySelectorAll('h4')
  const allH5 = document.querySelectorAll('h5')
  const allH6 = document.querySelectorAll('h6')
  const allParas = document.querySelectorAll('p')
  const allArticles = document.querySelectorAll('article')
  const allUnorderedLists = document.querySelectorAll('ul')
  const allOrderedLists = document.querySelectorAll('ol')
  const allListItems = document.querySelectorAll('li')
  const allAnchors = document.querySelectorAll('a')
  const allU = document.querySelectorAll('u')
  const allCode = document.querySelectorAll('code')
  const allButtons = document.querySelectorAll('button')
  const allSpans = document.querySelectorAll('span')

  // Black background
  body.style.backgroundColor = '#242424';
  allDivs.forEach(div => div.style.backgroundColor = '#242424')
  allArticles.forEach(div => div.style.backgroundColor = '#242424')
  allOrderedLists.forEach(ol => ol.style.backgroundColor = '#242424')
  allUnorderedLists.forEach(ul => ul.style.backgroundColor = '#242424')
  allListItems.forEach(li => li.style.backgroundColor = '#242424')
  allCode.forEach(code => code.style.backgroundColor = '#242424')
  allSpans.forEach(span => span.style.backgroundColor = '#242424')
  
  // White text
  allDivs.forEach(div => div.style.color = '#eee')
  allCode.forEach(code => code.style.color = '#eee')
  allOrderedLists.forEach(ol => ol.style.color = '#eee')
  allUnorderedLists.forEach(ul => ul.style.color = '#eee')
  allListItems.forEach(li => li.style.color = '#eee')
  allParas.forEach(para => para.style.color = '#eee')
  allH1.forEach(h1 => h1.style.color = '#eee')
  allH2.forEach(h2 => h2.style.color = '#eee')
  allH3.forEach(h3 => h3.style.color = '#eee')
  allH4.forEach(h4 => h4.style.color = '#eee')
  allH5.forEach(h5 => h5.style.color = '#eee')
  allH6.forEach(h6 => h6.style.color = '#eee')
  allAnchors.forEach(a => a.style.color = '#eee')
  allU.forEach(u => u.style.color = '#eee')
  allButtons.forEach(button => button.style.color = '#eee')
  allSpans.forEach(span => span.style.color = '#eee')
})()